export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  COLLEGE_ADMIN = "COLLEGE_ADMIN",
  COLLEGE_EDITOR = "COLLEGE_EDITOR",
}

export enum PostType {
  NEWS = "NEWS",
  BLOG = "BLOG",
  ANNOUNCEMENT = "ANNOUNCEMENT",
}

export enum PostStatus {
  DRAFT = "DRAFT",
  PENDING_REVIEW = "PENDING_REVIEW",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  APPROVED = "APPROVED",
  PUBLISHED = "PUBLISHED",
  REJECTED = "REJECTED",
  ARCHIVED = "ARCHIVED",
}

export enum ApprovalAction {
  SUBMIT = "SUBMIT",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  REQUEST_CHANGES = "REQUEST_CHANGES",
  PUBLISH = "PUBLISH",
  UNPUBLISH = "UNPUBLISH",
  ARCHIVE = "ARCHIVE",
}

export enum MediaType {
  IMAGE = "IMAGE",
  DOCUMENT = "DOCUMENT",
  VIDEO = "VIDEO",
  OTHER = "OTHER",
}
